# Dependencies
markdown:         kramdown
highlighter:      pygments
gems: [jekyll-gist]

# Permalinks
permalink:        pretty
#relative_permalinks: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Setup
title:            Twarit Waikar
tagline:          'Portfolio'
description:      'Software Engineer at Salesforce'
url:              https://chronicallyserious.github.io/
baseurl:          https://chronicallyserious.github.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

assets:
  resume:         /assets/Twarit_Waikar_Resume.pdf
